2 Q - ALGO EX - ERROR CHECK - SHOWS THAT I SHOULD USE CHAR INSTEAD OF CH
Cell In[6], line 22
     20 # Call the main function
     21 if __name__ == '__main__':
---> 22     main()

Cell In[6], line 12, in main()
      8 # Iterate through each chacter in the string
      9 for ch in my_string:
     10
     11 # Check if character is a space
---> 12     if char == '':
     13
     14 # Increment the counter
     15         count += 1
     17 # Print the result

NameError: name 'char' is not defined