2 Q - PROG EX - ERROR CHECK CALLING MAIN FUNCTION. REMOVED ' FROM END OF TOTAL, NOW MISSING COMMA
Cell In[14], line 13
    print('Sum of the single-digits entered is:' total)
          ^
SyntaxError: invalid syntax. Perhaps you forgot a comma?